version: 2

sources:
  - name: jaffle_shop
    database: raw
    description: This is a replica of the Postgres database used by our app
    tables:
      - name: orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        freshness: # default freshness
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: _etl_loaded_at
        columns:
          - name: id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time
        
      - name: customers
        description: This is a table of customers
        columns:
          - name: id
            description: Primary key of the customers table
            tests:
              - unique
              - not_null
          - name: first_name
            description: First name of the customer
          - name: last_name
            description: Last name of the customer

  - name: stripe
    database: raw
    tables:
      - name: payment